### ISSUE TITLE
导出为PDF时，脚注编号似乎不会上标

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-plugin-blockref-footnote#31]
![image](https://github.com/user-attachments/assets/07276b50-d11d-4916-acac-86d14c55d6c5)

**Comment by Achuan-2** [comment]
思源笔记的问题，块引导出会去掉上标
你可以添加css
```css
/* 导出pdf脚注引用为上标样式 */
.b3-typography a[custom-footnote],
#preview .protyle-wysiwyg a[custom-footnote] {
    top: -0.5em;
    font-size: 75%;
    line-height: 0;
    vertical-align: baseline;
    position: relative;
}
```
